"""One-time, anchor-checked manuscript revision; retained as an editing record."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
path = ROOT / 'docs/manuscript/main.tex'
t = path.read_text(encoding='utf-8-sig')

def paragraph(start, replacement):
    global t
    a = t.index(start)
    b = t.find('\n\n', a)
    assert b >= 0, start
    t = t[:a] + replacement + t[b:]

def span(start, end, replacement):
    global t
    a = t.index(start)
    b = t.index(end, a)
    t = t[:a] + replacement + '\n\n' + t[b:]

def exact(old, new):
    global t
    old = old.replace(chr(92)+chr(39), chr(39))
    assert old in t, old[:100]
    t = t.replace(old, new)

paragraph(r'\abstract{', r'''\abstract{Protecting drinking water sources requires timely information about conditions beyond directly monitored locations. This study presents a digital twin prototype integrating networked environmental observations, an established three-dimensional hydrodynamic water quality model, and source-protection applications at the Brusdalsvatnet reservoir in Norway. The contribution is the systems integration and the applications it enables; the governing equations and numerical solver are established methods. The framework connects state estimation for operational monitoring with contamination-scenario analysis and model-informed planning of uncrewed surface vessel sampling. Comparison of the revised thermal simulation with hourly observations at 2.95~m depth over the 2024 season gives a root-mean-square error of \texorpdfstring{1.73~$^{\circ}$C}{1.73 degrees Celsius} and a Pearson correlation of 0.962; mean depth-band RMSE is \texorpdfstring{2.15~$^{\circ}$C}{2.15 degrees Celsius}, with larger errors through the metalimnion. The contaminant scenario and sampling route demonstrate analytical capabilities but have not been validated in the field. Sensor retrieval is automated, while the complete operational update loop remains a proposed integration of implemented components. The results establish a proof of concept for source-water decision support and identify the measurements and operational testing needed before reliance on its predictions.}''')
paragraph('A digital twin is a model', '''A digital twin combines a representation of a physical system with observations that update knowledge of its state and support analysis and decisions. Applied to source-water protection, this framework can connect routine monitoring with spatial predictions and incident-response planning, particularly for constituents that cannot be monitored continuously.''')
paragraph('In this study, the authors investigated', r'''This study develops and demonstrates a systems-integration prototype for the Brusdalsvatnet drinking water reservoir in Norway. It builds on the sensing infrastructure and dashboard presented in \citep{primeau2024towards} by adding a three-dimensional modelling layer and applications for state estimation, contaminant-release analysis and model-informed mobile sampling. The contribution is the integration of these components in a source-protection workflow. The governing equations, discretization and solver are established methods; their development is not a contribution of this work.''')
paragraph('An earlier version of this work was posted', r'''An earlier version of this study was posted as a preprint \citep{primeau2025preprint}. The present article supersedes that version and presents the revised thermal evaluation, expanded model and sensor documentation, and explicit distinctions between demonstrated capabilities and proposed operational use.''')
paragraph('Water quality encompasses physical', r'''Water quality encompasses physical, chemical and biological properties that vary through a water body under the influence of sources, transport and reactions \citep{chapman2021water}. Some properties can be measured in situ using optical or electrochemical sensors, whereas many micropollutants and pathogenic organisms require specialized instruments or laboratory analysis \citep{zulkifli2018detection,Chidiac2023APerspectives}. Their spatial distributions are therefore generally less well observed than routine sensor variables such as temperature.''')
span('Modeling is another alternative', r'\subsection{Digital Twins}', r'''Process-based hydrodynamic water quality models (HWQM) represent circulation and constituent transport using conservation laws coupled to reaction formulations. Their capabilities and limitations have been studied extensively \citep{de2020historical,tsakiris2012water,Piccolroaz2024,Hipsey2020assessment}. This paper uses that established modelling approach as a component of the integrated system, rather than attempting to establish its general validity.

A process-based model provides an explicit, inspectable account of transport and reactions when observations of target constituents are sparse. Data-driven surrogates can also reproduce spatial water quality fields \citep{wang2025spatio,Mohammed2022EmulatingLearning}; the choice here reflects the available observations and the need to examine hypothetical releases through their constituent processes. It does not imply that physical models are universally more accurate or remove dependence on uncertain boundary conditions and parameters.

Three-dimensional resolution preserves variation in both horizontal directions and depth, supporting comparisons between sampling locations and the examination of subsurface plume pathways. One-dimensional models can reproduce vertical stratification, and laterally averaged two-dimensional models can represent depth-dependent transport; the required spatial detail depends on the application \citep{3D_better,Piccolroaz2024}. The three-dimensional representation was selected to support the spatial analyses in Section~\ref{ch:Experiments}. Its site-specific performance is assessed separately from the established numerical method.''')
paragraph('The essential feature of a digital twin', r'''Digital twin frameworks connect observations of a physical system with an updated virtual representation and functions for monitoring, prediction and analysis \citep{tao2018digital,barricelli2019survey}. For source-water protection, these functions correspond to estimating present conditions, exploring contamination scenarios and planning monitoring actions. An online dashboard provides an interface through which water managers can inspect observations and model results.''')
paragraph('Digital twins were originally conceived', r'''Digital twins are used across engineered and natural systems, with communication requirements and useful update intervals determined by the application \citep{alam2015design,verdouw2021digital}. In the water sector they support treatment and distribution operations \citep{MA2025108316,ConejosFuertes13092020}. For environmental monitoring, the one-to-three-hour latency described by Murphy et al. \citep{Murphy2015} provides a practical near-real-time target; whether an integrated modelling system meets it requires measurement of the full observation-to-publication interval.''')
# Remove private optimization narrative; retain the campaign actually used for Fig. 6.
span('Before operating the model online', r'\begin{figure}[t]', r'''The model configuration is assessed offline before use in an operational update loop. The historical campaign behind Figure~\ref{fig:meshconverge} compared horizontal meshes, vertical layer counts, water clarity, filtering, eddy coefficients and timestep controls. Its retained configuration-level results provide the cost--accuracy comparison in Section~\ref{ch:Calibrated}. The revised thermal simulation in Table~\ref{tab:performance} is a separate supplied configuration, documented in Appendix~\ref{app:modelconfig}; it is not one of the points in that historical campaign. The contaminant and mobile-sampling examples retain the earlier scenario outputs. These experiments demonstrate complementary parts of the framework and do not constitute a single identically configured simulation campaign.''')
exact(r'The first profiler profile of the season sets the initial temperature field; every later profile is withheld from the forcing and reserved for validation and model selection, so that no observation used to evaluate the model also drives it.', r'The initial profiler observation informs the initial temperature field; subsequent profiles are compared with model output rather than directly prescribed as temperatures within the simulated water column.')
# Shorten the hydrodynamic explanation while retaining equation labels for the diagrams.
paragraph('The process models module', r'''The process-model module in Figure~\ref{fig:IO} uses the Delft3D FM hydrodynamic and water quality solvers. The following equations summarize the standard hydrostatic formulation; discretization, closure and numerical solution are documented by Deltares \citep{D-WAQ_manual,de2020historical}. For an incompressible flow, constituent concentration $C_n$ obeys the advection--diffusion--reaction balance''')
exact(r'D_x \frac{\partial^2 C_n}{\partial x^2}-u \frac{\partial C_n}{\partial x}+D_y \frac{\partial^2 C_n}{\partial y^2}-v \frac{\partial C_n}{\partial y} +D_z \frac{\partial^2 C_n}{\partial z^2}-w \frac{\partial C_n}{\partial z}+\sum S(t,...)', r'\nabla\!\cdot(\mathbf{D}\nabla C_n)-\mathbf{u}\!\cdot\nabla C_n+\sum S_n')
paragraph(r'\noindent where $C_n$', r'''\noindent where $C_n$ has units of mass per volume, $\mathbf{u}=(u,v,w)$ is velocity, $\mathbf{D}$ is the dispersion tensor, and $S_n$ denotes source and sink rates per unit volume. The divergence form allows spatially varying dispersion coefficients. Heat transport uses the corresponding energy balance with surface heat-flux terms.''')
exact(r'+\frac{\partial \bar{u} h}{\partial x}+\frac{\partial \bar{v} h}{\partial y}', r'-\frac{\partial (\bar{u} h)}{\partial x}-\frac{\partial (\bar{v} h)}{\partial y}')
exact(r'$F_x$, $F_y$ are Reynolds stresses with dimensions of force; $M_x$, $M_y$ are external sources and sinks of momentum, such as interactions with structures, inflows or outflows.', r'$F_x$, $F_y$ represent horizontal stress-divergence contributions per unit mass; $M_x$, $M_y$ represent other momentum-source contributions. Each has dimensions of acceleration.')
paragraph('Using the shallow water assumption', r'''Under the hydrostatic approximation, vertical acceleration is neglected in the momentum balance. For incompressible flow away from volumetric sources, continuity gives''')
paragraph('Equations~\\ref{Eq:momentumx} and', r'''The momentum equations use Reynolds averaging, with unresolved turbulent transport represented by closure and eddy coefficients. The supplied thermal configuration uses the $k$-$\epsilon$ closure; its settings are given in Appendix~\ref{app:modelconfig}.''')
paragraph('Finally, it follows from the shallow water assumption', r'''The hydrostatic pressure relationship is''')
paragraph('Equations \\ref{Eq:advection-diffusion}', r'''Surface heat exchange, wind stress, bed friction, inflows, outflows and constituent reactions complete the forcing of this system. These established processes are configured for the case study rather than introduced as new numerical methods.''')
span('In principle it is possible to use water quality data', 'The model scripts are managed', r'''The first profiler observation informs the initial temperature field. Subsequent profiles are used to compare simulated and observed conditions rather than directly prescribing temperatures in interior cells. Figure~\ref{fig:IO} makes this distinction explicit.

Figure~\ref{fig:dataflow} shows the intended operational architecture. Newly retrieved observations would update model boundary conditions; model output would supply a spatial state estimate and the initial conditions for a later update. Alternative configurations could be compared against available observations before selecting an output for publication. This proposed operational ensemble is distinct from both the historical configuration comparison in Figure~\ref{fig:meshconverge} and the three reaction alternatives used for sampling-plan analysis.

The implemented components support data retrieval, input preparation, model execution, evaluation and display, but the full sequence has not been demonstrated as an unattended hourly loop. Scenario analysis and sampling-plan generation are demonstrated offline. Appendix~\ref{app:workflow} distinguishes implemented components from proposed automation and reports sensor coverage and measured solver throughput.''')
paragraph('The model scripts are managed', r'''Python scripts and Windows Task Scheduler support the implemented workflow. A local application provides access to model preparation and analysis, while the public dashboard described in \citep{primeau2024towards} displays monitoring data and selected outputs. Table~\ref{tab:computer} reports the computing environment for the supplied thermal-run throughput benchmark.''')
span('An automated workflow retrieves data', 'In this study, the Delft3D FM suite', r'''The acquisition scripts retrieve surface-sonde and weather observations hourly and vertical profiles twice daily. Offline comparison against the profiler record provides a check on the resulting thermal field. Evaluating both stratified and cooling periods exposes errors that may be less apparent over a short spring window; it does not by itself identify the process responsible for a discrepancy.''')
paragraph('In this study, the Delft3D FM suite', r'''Delft3D FM was selected for its established hydrodynamic and water quality capabilities and prior applications to seasonally stratified lakes \citep{Delft_Validation1}. Solver settings for the revised thermal run are recorded in Appendix~\ref{app:modelconfig}. The case study covers the open-water season: ice processes are not represented in this configuration, and the profiler is removed during winter to prevent damage.''')
exact(r'Operational model update loop, annotated with the rate at which each step runs: retrieval at each platform\'s publication interval, an hourly model run costing on the order of one second of computation per simulated hour, and a nowcast published less than two hours after the observations behind it. Two paths close the loop: model output becomes the next update\'s initial condition, and a planned sampling mission is carried to the vessel manually. Measured coverage and latency are reported in Appendix~\ref{app:workflow}.', r'Proposed operational update loop assembled from the prototype components. Surface-sonde and weather retrieval are hourly and vertical profiles are retrieved twice daily; vessel data transfer is manual. Model restart, selection and publication illustrate the intended integration rather than a demonstrated unattended loop. Implementation status, data coverage and solver throughput are reported in Appendix~\ref{app:workflow}.')
paragraph('As shown in Figure~\\ref{fig:dataflow}, the function', r'''The fixed profiler samples a single horizontal location. Mobile profiles can instead target locations where alternative model predictions differ, providing observations with which to compare those alternatives. Because each mission has limited time for transit and profiling, selecting a small set of such locations is a useful planning task.''')
paragraph('To compare the sensitivity of different model locations', r'''Alternative simulations are generated using different input or process assumptions. The retained sampling example uses the mean of the layer-wise standard deviations across $M$ model alternatives. For horizontal cell $i$ with $L_i$ active layers, the score is''')
exact(r'\sigma_i = \sqrt{\frac{1}{M} \sum_{m=1}^{M} \left(P_i^{(m)} - \mu_i\right)^2}', r'\sigma_i = \frac{1}{L_i}\sum_{\ell=1}^{L_i}\sqrt{\frac{1}{M}\sum_{m=1}^{M}\left(P_{i\ell}^{(m)}-\mu_{i\ell}\right)^2},\qquad \mu_{i\ell}=\frac{1}{M}\sum_{m=1}^{M}P_{i\ell}^{(m)}')
paragraph('Taking $S =', r'''Here $P_{i\ell}^{(m)}$ is the output concentration in layer $\ell$ of alternative $m$. The arithmetic layer mean matches the retained analysis; it is not a thickness-weighted depth average or the standard deviation of depth-averaged concentrations. The score measures model spread rather than a calibrated probability distribution. Scores are normalized as $\sigma_i'=\sigma_i/\max_j\sigma_j$ when the maximum is positive. This common scaling leaves rankings and relative cluster weights unchanged. The $r$ highest-scoring cells are selected as''')
paragraph('Finally, given a start and end point', r'''For a specified launch-and-recovery point $\mathbf{c}_0$, a brute-force search selects the ordered sequence of distinct cluster centroids with maximum summed weight under a route-length budget $D_{\max}$. Distances include travel from and back to the launch point:''')
span(r'    C^* = \argmax_', r'\label{eq:optimizer1}', r'''    C^* = \argmax_{\substack{(k_1,\ldots,k_q)\text{ distinct} \\ d(\mathbf{c}_0,\mathbf{c}_{k_1})+\sum_{j=1}^{q-1}d(\mathbf{c}_{k_j},\mathbf{c}_{k_{j+1}})+d(\mathbf{c}_{k_q},\mathbf{c}_0)\leq D_{\max}}}\sum_{j=1}^{q}w_{k_j}
''')
exact('The single horizontally-well-mixed main basin with strong seasonal stratification makes calibrating to all depths from a single horizontal point relatively reliable.', 'The main basin is seasonally stratified; the fixed profiler provides detailed vertical observations at one horizontal location.')
span('Physical features of Brusdalsvatnet', 'Previous assessment has identified', r'''Physical features, sensing locations and the five scenario-analysis sites are mapped in Figure~\ref{fig:map}. Hydrological boundary conditions are externally supplied time series of tributary discharge, outlet flow and water abstraction, applied at eight tributaries and the two principal withdrawals. Their generation is outside the scope of this integration study. The revised thermal run uses time-varying supplied forcing; the earlier scenario outputs were generated with an earlier model and forcing configuration.

Third-party lake-level and outflow records contribute to the provenance of the supplied hydrological inputs and are not distributed with the public analysis package. Comparison with the available water-level observations gives RMSE 0.027~m and Pearson correlation 0.987 over 3,180 paired values, after aligning the level datum. These aggregate indicators describe agreement of the supplied model output with the monitoring record; the availability limits are stated in the Data Availability Statement.''')
paragraph('Figure~\\ref{fig:meshconverge} presents', r'''Figure~\ref{fig:meshconverge} compares accuracy and cost in the historical configuration campaign. Its vertical axis is the mean of depth-wise temperature RMSE values; the horizontal axis is the dimensionless ratio of simulated time to wall-clock time. The plotted runs share the 25 April--20 November 2024 period. Shorter runs are excluded to avoid comparing errors accumulated over different seasonal windows. These serial runs were performed on a separate workstation, so their throughput is not directly comparable with the partitioned thermal-run benchmark in Appendix~\ref{app:workflow}. Colour denotes Pearson correlation. The vertical line shows the range across configurations sharing a mesh and layer count, not a sampling confidence interval.''')
paragraph('Two results follow.', r'''At 40 layers, increasing the number of 3D cells from 36,197 to 65,900 changes RMSE from 1.336 to 1.325~$^{\circ}$C for a 1.6-fold increase in runtime. At fixed resolution, changing other settings spans RMSE values from 1.076 to 2.852~$^{\circ}$C. Thus, for this observation-based comparison, physical settings have a larger effect than the tested refinement. This is a limited resolution/configuration comparison, not proof of grid-independent transport. The revised thermal configuration evaluated below was supplied separately and is not one of the plotted candidates; Figure~\ref{fig:meshconverge} does not describe its optimization history.''')
paragraph('Importantly, the simulation runs', r'''For context, Feldbauer et al. \citep{hess-29-1183-2025} compared four calibrated one-dimensional lake-temperature models across 73 lakes. The best-performing model for each lake gave median RMSE 1.2~$^{\circ}$C and median correlation 0.98, with 95\% below 2~$^{\circ}$C. These values provide literature context rather than operational acceptance thresholds; observation coverage, dimensionality and error aggregation differ between studies.''')
paragraph('Table~\\ref{tab:performance} reports', r'''Table~\ref{tab:performance} reports the revised thermal simulation over 22 April--20 November 2024. Agreement varies with depth: RMSE is 1.12~$^{\circ}$C at 7~m, reaches 3.07~$^{\circ}$C at 18~m and is 1.57~$^{\circ}$C at 50~m. Twenty-three of the fifty depth bands have RMSE below 2~$^{\circ}$C. The final-error column records model minus observation at the last available paired time at each depth; it is not mean seasonal bias. The profile and residual plots in Appendix~\ref{app:tempvalidation} show excessive warming below the surface during stratification.''')
paragraph('The degradation relative to shorter simulations', r'''The full-season comparison exposes errors that a short spring window would not characterize. Because the historical and revised runs also differ in configuration, the difference between their scores cannot be attributed to simulation duration alone. The model captures broad seasonal thermal evolution, but the stratified-period discrepancies limit quantitative interpretation of subsurface temperatures and associated transport.''')
exact(r'\textbf{Bias}', r'\textbf{Final error}')
exact(r'\textbf{Bias ($^{\circ}$C)}', r'\textbf{Final error ($^{\circ}$C)}')
exact('Selected model configuration performance, 2024 season.', 'Revised thermal configuration performance, 2024 season. Final error is model minus observation at the last paired time; the depth-band mean row reports mean sample count and mean statistics across bands.')
paragraph('Once the model is calibrated, it can also', r'''A configured HWQM can be used offline to examine the transport consequences of a hypothetical contaminant release. The example here concerns construction-related nitrogen inputs and illustrates how the integrated framework supports scenario analysis. Figures~\ref{fig:contam} and \ref{fig:contamtime1} retain outputs from an earlier scenario configuration, not the revised thermal run in Table~\ref{tab:performance}. No release was observed, and the sparse laboratory nitrogen samples cannot resolve a transient plume. These outputs therefore demonstrate the analysis workflow rather than validated concentration forecasts.''')
paragraph('Based on the analysis of a consultant', r'''The consultant's contingency scenario is a release of 3.5~kg of ammonium nitrate (NH$_4$NO$_3$). Dissociation gives equal molar amounts of ammonium and nitrate, corresponding to approximately 0.6125~kg ammonium-N and 0.6125~kg nitrate-N (1.225~kg total N). This is compound mass, not 3.5~kg of nitrogen. The original source-loading file is not retained with the exported scenario results, so the loading represented by Figures~\ref{fig:contam} and \ref{fig:contamtime1} cannot be reconciled quantitatively with this mass from the public artifacts alone. Their absolute concentration scale is consequently reported as archived model output, without a quantitative conclusion about the consequences of the specified 3.5~kg release. Concentrations are expressed as gN/m$^3$.''')
span('The meteorological forcing for this simulation', 'The simulated dispersal of the contaminant plume', r'''The earlier scenario uses meteorological forcing assembled for that experiment and a simulation beginning in spring to establish conditions before the release. Coverage statistics for the separately supplied revised thermal forcing are reported in Appendix~\ref{app:workflow}; they should not be read as the provenance of the earlier scenario.''')
paragraph('The magnitude of these predictions', r'''Routine grab samples provide scale context: the retained in-lake records span 0.001--0.011~gN/m$^3$ ammonium and 0.079--0.120~gN/m$^3$ nitrate. These observations concern background conditions, not the hypothetical plume, and do not establish an analytical detection threshold for an increment above background.''')
paragraph('On that basis the simulated worst case', r'''The archived outputs show a strongly localized early peak and smaller depth-averaged concentrations at the other sites. A depth average at the intake location does not establish concentration at the abstraction depth. Neither these outputs nor background variability establish that an increment would be undetectable or that mitigation is unnecessary. Appendix~\ref{app:massbalance} reports a separate nutrient-run balance; it does not verify conservation for this release scenario.''')
paragraph('Analysis of the contamination scenario can be used', r'''For a decision about mitigation, the scenario would require a verified source loading, intake-depth predictions, transport-specific numerical checks and an assessment of relevant uncertainties. The present demonstration shows how spatial and temporal model output can organize that analysis and identify monitoring locations; it does not establish intervention effectiveness.''')
exact('Modeled concentration of ammonium in gN/m$^3$ 12 hours post-release', 'Archived scenario concentration of ammonium in gN/m$^3$ 12 hours post-release')
exact('Modeled concentration in gN/m$^3$ of ammonium and nitrate.', 'Archived scenario output: depth-averaged ammonium and nitrate concentrations at five sites, in gN/m$^3$, versus time after release. Lines show model output, not measured concentrations; the original source loading has not been verified against the specified compound mass.')
exact('The standard deviation of the depth-averaged ammonium concentration in each 2D cell from the population of the three alternative predictions at the final timestep', 'The mean layer-wise standard deviation of ammonium concentration across the three alternatives at the final timestep')
span('The individual 2D cells are ranked', 'This data collection plan is exported', r'''The retained set of 51 highest-scoring cells is clustered using DBSCAN with a 100~m neighbourhood and a minimum of one cell per cluster. These are practical settings for the demonstration, chosen to reduce the number of nearby visits; they do not establish physical independence between cells or optimal sampling density. The resulting six clusters are labelled A--F, and each centroid is assigned the sum of its member scores.

The distance budget is 6~km, an illustrative limit for a supervised mission rather than a battery limit. At 2~kn it allows approximately 1.6~h of transit; profiling, launch and recovery require additional time. The shortest return journey to Cluster B alone is approximately 11.8~km, so its high weight cannot make it feasible within this budget. The selected route visits A, F, C and D before returning to the launch point, travelling 5,647~m. It maximizes the summed cluster score and then minimizes distance under the stated assumptions. Shoreline obstacles, profiling duration and time-varying information value are not optimized.

Appendix~\ref{app:stability} examines sensitivity of the downstream clustering and selected geographical regions to resampling the retained cells. This does not test the model spread against additional simulation alternatives.''')
exact('it was not flown', 'it was not executed')
exact(r'Data collection planning steps (\textbf{a}) estimated model sensitivity as input; (\textbf{b}) sensitive area clusters, collection sites and path as output.', r'Data collection planning from the retained 51-cell dataset: (\textbf{a}) normalized model-spread scores at the retained cells; (\textbf{b}) clusters, normalized cluster weights and selected route. Cluster labels and weights are generated from the same dataset as the optimization; the full-domain model-spread field was not retained.')
# Replace repetitive discussion and conclusions, retaining the substantive limitations.
span(r'\section{Discussion}', r'%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'+'\n'+r'\authorcontributions', r'''\section{Discussion}
\label{ch:Discussion}
The prototype connects monitoring observations with spatial modelling and source-protection analyses. Its practical contribution is the ability to use a common information workflow for inspecting conditions, exploring scenarios and identifying mobile sampling locations. It supports the information needs of a water safety plan; it does not replace treatment barriers, management procedures or the water supplier's assessment of an incident.

The thermal comparison demonstrates agreement in broad seasonal evolution and substantial discrepancies below the surface during stratification. Temperature agreement alone does not establish the velocity field driving constituent transport: different combinations of mixing, surface exchange and forcing can produce similar temperatures while producing different circulation \citep{hess-26-3651-2022}. Evaluation of state variables, process rates and system behaviour provides complementary evidence \citep{Hipsey2020assessment}. Current measurements or tracer observations would strengthen the transport assessment, but are not available for this demonstration.

The nitrogen scenario and the sampling plan are conditional demonstrations. The archived nitrogen source loading and transport convergence remain unverified, and a balance from another run does not resolve those limitations. The three reaction alternatives provide a model-spread score, not a complete uncertainty characterization. Cell resampling tests the downstream planning algorithm but cannot establish robustness to additional model alternatives. Field comparison with alternative sampling strategies is needed to determine whether the proposed planning method improves information gained per mission.

Sensor gaps and the distinction between implemented components and an unattended service also limit operational maturity. Appendix~\ref{app:workflow} reports data coverage and solver throughput. Publication latency, recovery from failures and clear indication of stale output require end-to-end testing before operational reliance.

\section{Conclusions}
\label{ch:Conclusions}
This study demonstrates a digital twin prototype integrating networked observations, an established three-dimensional model and applications for source-water protection. The contribution is the systems integration and its use for state estimation, hypothetical-release analysis and mobile-sampling planning. The numerical method and solver are established components.

For the revised thermal run, hourly temperature at 2.95~m agrees with observations at RMSE 1.73~$^{\circ}$C and Pearson correlation 0.962; the mean depth-band RMSE is 2.15~$^{\circ}$C, with larger metalimnetic errors. Chemical predictions and the sampling strategy remain unvalidated demonstrations, and the complete unattended operational loop has not been established. These limits distinguish the capabilities of the framework from the evidence provided by this case study.

The framework is potentially transferable, subject to local bathymetry, forcing, hazards, instrumentation and institutional capacity \citep{daniel2023survey}. Priorities for further work are transport validation, field evaluation of sampling strategies and testing the integrated update and publication workflow. Replication in other reservoirs would establish the conditions under which the architecture provides useful decision support.''')
span(r'\dataavailability{', r'\acknowledgments', r'''\dataavailability{Analysis code and retained derived datasets used for the manuscript figures are available at \url{https://github.com/russellprimeau/Postprocess}. The repository documents which plots can be regenerated from those artifacts. The configuration accompanying the revised thermal result is provided for interpretation; it is not the configuration of every historical experiment. The complete simulation and private tuning workflows are not part of the public analysis package. Re-running the underlying models requires a separately obtained, appropriately licensed Delft3D installation and the relevant original inputs. Hydrological forcing is supplied externally; protected third-party source records and their generation methods are outside the public study package. Original release-loading and per-alternative full-domain fields are not retained with the archived scenario exports. Consequently, reproduction of the supplied plots should not be equated with complete reproduction of the underlying simulations.}

''')
paragraph('Table~\\ref{tab:CalibrationMethod} brings', r'''Table~\ref{tab:CalibrationMethod} combines manufacturer specifications with the operational calibration record. Calibration offsets summarize adjustments across events; their standard deviation is not the uncertainty of an individual environmental measurement. In particular, the turbidity offsets span a wide range relative to the lake's low background signal, so this channel is not used as a quantitative model input. Manufacturer accuracy statements apply under their specified conditions and are distinct from field performance.''')
paragraph('Table~\\ref{tab:modelconfig} reports', r'''Table~\ref{tab:modelconfig} records the supplied configuration of the revised thermal simulation evaluated in Table~\ref{tab:performance} and Appendix~\ref{app:tempvalidation}. It does not describe the historical configuration campaign in Figure~\ref{fig:meshconverge} or the earlier contaminant and sampling demonstrations. No private optimization procedure is part of the study reported here.''')
exact('Horizontal grid & Unstructured, 4,935 2D cells', 'Horizontal grid & Unstructured, 4,936 faces in supplied mesh')
span(r'\begin{table}[H]'+'\n'+r'    \centering'+'\n'+r'    \caption{Parameters tuned', r'\section[\appendixname~\thesection]{Temperature Validation', '')
paragraph('The three panels show one error', r'''The panels show that agreement depends on both depth and season. At 1~m the seasonal pattern is reproduced with Pearson correlation 0.959. At 20~m the simulated summer temperatures exceed the observations substantially. At 50~m the discrepancy grows through summer and early autumn before declining during cooling; it is not a constant offset. The residuals in Figure~\ref{fig:thermalresiduals} show model minus observation at matched times and depths.''')
paragraph('This is the signature of excessive', r'''These patterns are consistent with excessive downward heat transport during stratification, but the temperature comparison alone does not isolate a particular mixing or surface-flux parameter as the cause.''')
paragraph(' The nowcast is reliable', r'''The mean depth-band statistics summarize seasonal agreement; they are not bounds on peak errors or a guarantee of operational accuracy at a particular depth.''')
paragraph('Concentrations produced by a transport scheme', '''This appendix reports a conservation diagnostic from a separate nutrient simulation. It is not a mass-balance check of the archived release scenario.''')
exact('Residual as \\% of largest term & 0.015\\% & 0.42\\%', 'Residual / maximum absolute load, reaction or net export & 0.0085\\% & 0.42\\%')
span('The balance closes to within', r'\section[\appendixname~\thesection]{Operational Workflow', r'''The residual is the stock change minus the signed loads, boundary contributions and reactions, calculated before rounding. The percentages use the largest absolute contribution among loads, reactions and net boundary export as denominator. For example, 0.31/3,640 is approximately 0.0085\% for ammonium. The displayed stock and flux terms are rounded and need not reproduce the smaller residual exactly.

This result describes conservation in that nutrient run only. It does not establish conservation, source loading or transport accuracy in Figures~\ref{fig:contam}--\ref{fig:contamtime1}. Numerical diffusion can redistribute mass while conserving the total; a release-specific balance and transport-resolution comparison remain necessary before quantitative reliance on that scenario.''')
span('The prototype is automated from data retrieval', r'\subsection{Data coverage}', r'''The implemented components support the stages in Table~\ref{tab:automation}. They have not been demonstrated as one unattended hourly service.

\begin{table}[H]
\centering
\caption{Implementation status and intended operational use.\label{tab:automation}}
\footnotesize
\begin{tabularx}{\textwidth}{@{}l X@{}}
\toprule
\textbf{Component} & \textbf{Status and cadence} \\
\midrule
Surface-sonde and weather retrieval & Automated acquisition; hourly records \\
Vertical-profile retrieval & Automated acquisition; twice-daily profiles \\
Quality control and forcing preparation & Implemented processing; coordinated for the reported runs \\
Model execution and post-processing & Implemented tools; unattended hourly orchestration not demonstrated \\
Model selection and restart & Proposed steps in the integrated operational loop \\
Dashboard & Implemented display; automatic publication after each model update not demonstrated \\
Scenario and sampling analysis & Implemented and demonstrated offline \\
Configuration changes & Manual \\
USV launch, recovery and data transfer & Manual, per mission \\
\bottomrule
\end{tabularx}
\end{table}''')
paragraph('Table~\\ref{tab:coverage} reports', '''Table~\\ref{tab:coverage} reports the coverage of observations and supplied meteorological forcing associated with the revised thermal simulation. It does not characterize the earlier release scenario.''')
exact('Water level & 62.4\\% & 3,178 of 5,089 hourly intervals', 'Water level & 62.4\\% & 3,178 distinct hourly intervals; 3,180 paired records')
span('Two features of this record', r'\subsection{Latency}', r'''The supplied meteorological dataset is complete after gap filling, with provenance tags identifying 94.0\% station observations and 6.0\% reanalysis. These percentages describe the supplied dataset, not an operational retrieval success rate. Missing temperature observations are omitted from the pointwise comparisons; model values are interpolated to available observation times and depths.''')
span(r'\subsection{Latency}', r'\section[\appendixname~\thesection]{Stability', r'''\subsection{Computational throughput and latency}

Nine supplied full-season runs with a common mesh and vertical discretization completed 212 simulated days in a median 32.5~minutes under twelve MPI partitions on the machine in Table~\ref{tab:computer}. This corresponds to approximately 9,400 simulated seconds per wall-clock second. It is a solver-throughput benchmark, not a measured duration for an hourly restart or an end-to-end operational update. It is also distinct from the serial historical campaign behind Figure~\ref{fig:meshconverge}.

Hourly acquisition makes near-real-time updates a plausible target, but total latency also includes retrieval, preparation, model execution, selection and publication. The full interval has not been measured. Twice-daily profiles additionally have a coarser observation cadence. The framework therefore does not claim a demonstrated under-two-hour publication latency.

\subsection{Robustness}

Gap handling and data-quality processing are implemented components. End-to-end behaviour under retrieval failures, incomplete forcing and failed simulations has not been established through operational testing. Retention of the last successful output, explicit timestamps and stale-data alerts are requirements for a future unattended service, rather than demonstrated properties of this prototype.''')
# Stability text will be replaced with the corrected analysis results separately.
span('The model spread driving the sampling plan', r'%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'+'\n'+r'%\isPreprints', r'''The retained planning input comprises 51 cells selected using three model alternatives. Leave-one-cell-out and 2,000 bootstrap replicates (random seed 20240401) repeat clustering and route selection. Geographical regions are identified by original cell membership, so DBSCAN label renumbering does not count as a different selected region. A bootstrap duplicate contributes to centroid and weight calculation, as in resampling the input rows.

\input{sampling_stability_results.tex}

The results characterize the dependence of downstream planning on the retained cells, conditional on their scores and the fixed route budget. They are not confidence intervals for the concentration predictions, and resampling spatial cells does not test additional process-model alternatives. The full per-alternative fields were not retained with this analysis package, so robustness of the initial model-spread ranking to additional alternatives remains untested.''')
exact('50m', '50~m')
exact('2.95m', '2.95~m')
t = t.replace('Independent ground-truth', 'Ground-truth')
path.write_text(t, encoding='utf-8')
print('Updated', path)
