; number of active and inactive substances
12             1
        ; active substances
1            'AAP' ;adsorbed ortho phosphate
2            'DetC' ;Detritus Carbon  (DetC)
3            'DetN' ;Detritus Nitrogen (DetN)
4            'DetP' ;Detritus Phosphorus (DetP)
5            'GREEN' ;Algae (non-Diatoms)
6            'NH4' ;Ammonium (NH4)
7            'NO3' ;Nitrate (NO3)
8            'PO4' ;Ortho-Phosphate (PO4)
9            'OXY' ;Dissolved Oxygen
10            'Cl' ;Chloride
11            'IM1' ;inorganic matter (IM1)
12            'Opal' ;inorganic silica (opal)
        ; passive substances
13            'SOD' ;Sediment oxygen demand (SOD)
