CONSTANTS 'CLOSE_ERR' DATA 1 ; If defined, allow delwaq to correct water volumes to keep concentrations continuous
CONSTANTS 'NOTHREADS' DATA 2 ; Number of threads used by delwaq
CONSTANTS 'DRY_THRESH' DATA 0.001 ; Dry cell threshold
CONSTANTS 'maxiter' DATA 200 ; Maximum number of iterations
CONSTANTS 'tolerance' DATA 1E-07 ; Convergence tolerance
CONSTANTS 'iteration report' DATA 0 ; Write iteration report (when 1) or not (when 0)
